apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kometa
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./apps/kometa  # Path to the Helm chart for Kometa
      sourceRef:
        kind: GitRepository
        name: home-lab  # The GitRepository resource
        namespace: flux-system
  values:
    replicaCount: 1
    persistence:
      size: 10Gi
      accessMode: ReadWriteOnce
      storageClass: microk8s-hostpath
    media:
      moviesPath: /new-pool/media/movies
      tvshowsPath: /new-pool/media/tvshows
    plex:
      url: "http://192.168.1.2:32400"
      token: "Z1-9suDV6Q9vEbnseeNr"
    metadata:
      fetchInterval: "24h"
