apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kometa
  namespace: default
spec:
  chart:
    spec:
      chart: ./apps/kometa
      sourceRef:
        kind: GitRepository
        name: home-lab
        namespace: flux-system
  values:
    replicaCount: 1
    persistence:
      size: 10Gi
      accessMode: ReadWriteOnce
      storageClass: microk8s-hostpath
    service:
      port: 80
