apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kometa-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/microk8s/kometa
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-lab
  validation: client
