apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kometa
  namespace: default
spec:
  interval: 5m  # Reconcile every minute
  chart:
    spec:
      chart: ./apps/kometa  # Path to the Helm chart for Kometa
      sourceRef:
        kind: GitRepository
        name: home-lab
        namespace: flux-system
  values:
    replicaCount: 1
    media:
      moviesPath: /media/movies
      tvshowsPath: /media/tvshows
    metadata:
      fetchInterval: "24h"
    image:
      repository: kometateam/kometa  # Correct image repository
      tag: latest                    # Specify the tag
      pullPolicy: Always
    secretEnv:  # Section to handle secret values
      plex:
        url:
          name: kometa-secrets
          key: PLEX_URL
        token:
          name: kometa-secrets
          key: PLEX_TOKEN
