apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kometa
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/microk8s/flux-system/kometa
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-lab
    namespace: flux-system
