apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa-cronjob
  namespace: default
spec:
  schedule: "{{ .Values.schedule }}"  # Uses the schedule from values.yaml
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kometa
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            env:
              - name: PLEX_URL
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secretEnv.plex.url.name }}  # Reference the Secret for Plex URL
                    key: {{ .Values.secretEnv.plex.url.key }}    # The key in the Secret
              - name: PLEX_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.secretEnv.plex.token.name }}  # Reference the Secret for Plex token
                    key: {{ .Values.secretEnv.plex.token.key }}    # The key in the Secret
              - name: MOVIES_DIR
                value: "{{ .Values.media.moviesPath }}"
              - name: TVSHOWS_DIR
                value: "{{ .Values.media.tvshowsPath }}"
              - name: FETCH_INTERVAL
                value: "{{ .Values.metadata.fetchInterval }}"
            volumeMounts:
              - name: movies-volume
                mountPath: /media/movies
              - name: tvshows-volume
                mountPath: /media/tvshows
          volumes:
          - name: movies-volume
            hostPath:
              path: "{{ .Values.media.moviesPath }}"
              type: Directory
          - name: tvshows-volume
            hostPath:
              path: "{{ .Values.media.tvshowsPath }}"
              type: Directory
          restartPolicy: OnFailure
