apiVersion: apps/v1
kind: Deployment
metadata:
  name: kometa
  labels:
    app: kometa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kometa
  template:
    metadata:
      labels:
        app: kometa
    spec:
      containers:
      - name: kometa
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: movies-volume
          mountPath: /media/movies
        - name: tvshows-volume
          mountPath: /media/tvshows
      volumes:
      - name: config-volume
        hostPath:
          path: {{ .Values.persistence.hostPath }}
      - name: movies-volume
        hostPath:
          path: {{ .Values.media.moviesPath }}  # Path on host for Movies
      - name: tvshows-volume
        hostPath:
          path: {{ .Values.media.tvshowsPath }}  # Path on host for TV Shows
